version: "3"
services:
  meilisearch-0.26.0rc1:
    image: "getmeili/meilisearch:v0.26.0rc1"
    container_name: "meilisearch"
    ports:
      - "7720:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_NO_SENTRY=true
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - meilisearch_data:/data.ms
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.search.rule=Host(`search.ghislain-lerda.fr`)"
      - "traefik.http.routers.search.entrypoints=websecure"
      
networks:
  proxy:
    external: true
    
volumes :
  meilisearch_data:
